### ISSUE TITLE
When I visit the home page, I want to see the logo, explanation of the site, and a button to see the list of roles.

### ISSUE THREAD

**Issue by m4v15** [FACN1/VolunteerApp#35]
For #33 
## Technical tasks

- [x] Build Server using Express, using handlebars for templating, that servers up the home page view on '/' (#45).
- [x] Make default layout for handlebars(#46).
- [x] Make view for homepage (#47).
- [ ] Do CSS for home page view (#48).

**Comment by m4v15** [comment]
## Technical tasks

1. Build Server using Express, using handlebars for templating
2. Make default layout for handlebars
3. Make view for homepage
